function available_movies(fig)

uibuttongroup('Visible','on',... 
              'BackgroundColor','#D6CADD',... 
              'ForegroundColor','black',... 
              'Title','',... 
              'FontSize',14,... 
              'TitlePosition','centertop',...                
              'Position', [ 0.05 0.44 0.28 0.5]);

    %'Select Movie Date:'
    uicontrol('Style', 'text', ...
              'Units', 'normalized', ...
              'FontSize', 14, ...
              'FontWeight', 'bold', ...
              'BackgroundColor', '#D6CADD', ...
              'Position', [0.1 0.74 0.2 0.15], ...  
              'String', 'Select Movie Date:'); 

    %button to pick a date
    uicontrol('Style', 'pushbutton', ... 
              'Units', 'normalized', ... 
              'Fontsize', 14, ... 
              'BackgroundColor', '#ADD8E6', ... 
              'Position', [0.1 0.8 0.2 0.05], ...  
              'String', 'Pick date', ... 
              'Callback', @(src, event) pick_date_callback(src, event, fig));

    %'Date selected:'
    uicontrol('Style', 'text', ...
              'Units', 'normalized', ...
              'FontSize', 14, ...
              'FontWeight', 'bold', ...
              'BackgroundColor', '#D6CADD', ...
              'Position', [0.1 0.735 0.2 0.05], ...  
              'String', 'Date selected:'); 

    %'No date selected'
    date_display = uicontrol('Style', 'text', ...
                            'Units', 'normalized', ...
                            'FontSize', 14, ...
                            'FontWeight', 'normal', ...
                            'BackgroundColor', '#D6CADD', ...
                            'Position', [0.1 0.7 0.2 0.05], ...  
                            'String', 'No date selected   '); 

    %store date_display handle in the figure's UserData
    fig.UserData.date_display = date_display;

    %'Select Movie Genre:'
     uicontrol('Style', 'text', ...
              'Units', 'normalized', ...
              'FontSize', 14, ...
              'FontWeight', 'bold', ...
              'BackgroundColor', '#D6CADD', ...
              'Position', [0.1 0.50 0.2 0.15], ... 
              'String', 'Select Movie Genre:');  

     %dropdown menu
        genre_dropdown = uicontrol('Style', 'popupmenu', ...
                                  'Units', 'normalized', ...
                                  'Position', [0.1, 0.55, 0.2, 0.04], ...  
                                  'FontSize', 12, ...
                                  'BackgroundColor', '#FFFFFF', ...
                                  'String', {'None', 'Animation', 'Action', 'Drama', 'Comedy', 'Horror', 'Romance', 'Mystery'}, ...
                                  'Enable', 'off', ...  
                                  'Callback', @(src, event) genre_selection_callback(src, event, fig)); 
      
        %store genre_dropdown handle in the figure's UserData
        fig.UserData.genre_dropdown = genre_dropdown;
    end

%genre selection callback
function genre_selection_callback(src, event, fig)
    %get the current date from the figure
    date_display = fig.UserData.date_display;
    selected_date = date_display.String; %get the date string
    
    %if a date is selected, get the selected genre
    genres = src.String;
    selected_option = genres{src.Value};%get the selected genre
        
    %call the display_movies function
    display_movies(fig, selected_date);    
end