function buy_ticket(fig)

 % Add slider label
    uicontrol('Style', 'text', ...
              'Parent', fig, ...
              'Units', 'normalized', ...
              'Position', [0.01 0.85 0.2 0.05], ...
              'FontSize', 12, ...
              'FontWeight', 'bold', ...
              'BackgroundColor', '#FAF3E0', ...
              'String', 'Adjust Ticket Quantity:');

    % Add slider
    slider = uicontrol('Style', 'slider', ...
                       'Parent', fig, ...
                       'Units', 'normalized', ...
                       'Position', [0.01 0.8 0.2 0.05], ...
                       'Min', 1, 'Max', 10, 'Value', 5, ...
                       'SliderStep', [1/9, 1/9], ...
                       'Callback', @(src, event) sliderCallback(src, event, fig));  

    % Add text to display slider value
    ticketDisplay = uicontrol('Style', 'text', ...
                              'Parent', fig, ...
                              'Units', 'normalized', ...
                              'Position', [0.01 0.75 0.2 0.05], ...
                              'FontSize', 12, ...
                              'BackgroundColor', '#FAF3E0', ...
                              'String', 'Tickets: 5');  

     % Store display handle in figure UserData for updating
    fig.UserData.ticketDisplay = ticketDisplay;
    fig.UserData.selectedMovie = '';
    fig.UserData.enteredDate = '';

    moviesDropdown = uicontrol('Style', 'popupmenu', ...
                                  'Units', 'normalized', ...
                                  'Position', [0.01, 0.56, 0.22, 0.04], ... 
                                  'FontSize', 12, ...
                                  'BackgroundColor', '#FFFFFF', ...
                                  'String', {'Ten things I hate about you', 'Titanic', 'Where The Crawdads Sing', 'Watcher', 'Lord of the rings', 'The wicked', 'The Conductor', 'Wonder ', 'Fast & Furious 9 ', 'Spider-Man ', 'Home Alone', 'Scary Movie ', 'Orphan ', 'Smile 2 '}, ...
                                  'Enable', 'on', ... 
                                  'Callback', @(src, event) movieSelectionCallback(src, fig));

    uicontrol('Style', 'text', ...
              'Units', 'normalized', ...
              'FontSize', 12, ...
              'FontWeight', 'bold', ...
              'BackgroundColor', '#FAF3E0', ...
              'Position', [0.04 0.6 0.1 0.05], ...  
              'String', 'Select movie:');
    
    uicontrol('Style', 'text', ...
              'Units', 'normalized', ...
              'FontSize', 12, ...
              'FontWeight', 'bold', ...
              'BackgroundColor', '#FAF3E0', ...
              'Position', [0.01 0.69 0.15 0.05], ...  
              'String', 'Enter date:');

     % Text box for date input
    dateInput = uicontrol('Style', 'edit', ...
                          'Parent', fig, ...
                          'Units', 'normalized', ...
                          'Position', [0.13 0.7 0.1 0.045], ... 
                          'BackgroundColor', [0.9, 0.9, 0.9], ...
                          'ForegroundColor', 'black', ...
                          'FontSize', 12, ... 
                          'String', '', ... % Start with an empty box
                          'Callback', @(src, ~) dateInputCallback(src, fig));

    uicontrol('Style','pushbutton',... 
              'Parent', fig, ...
              'Units','normalized',... 
              'FontSize', 14,... 
              'BackgroundColor','#ADD8E6',... 
              'Position',[0.01 0.2 0.2 0.1],... 
              'String','Buy ticket', ...
              'Callback', @(src, event) buyTicketCallback(fig));

most_watched_movies(fig);
  
end

function sliderCallback(src, ~, fig)
    % Update the ticket display with the rounded slider value
    currentValue = round(src.Value); 
    fig.UserData.ticketDisplay.String = ['Tickets: ', num2str(currentValue)];
end

function movieSelectionCallback(src, fig)
    % Update the selected movie in UserData
    movies = src.String;
    selectedIndex = src.Value;
    fig.UserData.selectedMovie = movies{selectedIndex};
end

function dateInputCallback(src, fig)
    % Update the entered date in UserData
    fig.UserData.enteredDate = src.String;
end

function buyTicketCallback(fig)
    % Get the necessary data
    ticketDisplay = fig.UserData.ticketDisplay.String;
    numTickets = str2double(regexp(ticketDisplay, '\d+', 'match', 'once'));
    selectedMovie = fig.UserData.selectedMovie;
    enteredDate = fig.UserData.enteredDate;

    % Display confirmation message
    msg = sprintf('You bought %d tickets for %s for the movie %s', ...
                  numTickets, enteredDate, selectedMovie);
    msgbox(msg, 'Purchase Confirmation');
end

