function createfig(avin, fig)

 %if the user pushed the "Available movies" button, the title of the figure becomes "Available movies" and variable avin=0 
    if avin == 0  
        figurename = "Available movies"; 
    else  
        % if the user pushed the "Buy ticket" button, the title of the figure becomes "Buy ticket" and variable avin=1 
        figurename = "Buy ticket"; 
    end

    %create the figure with the specified title
    fig = figure('Name', figurename, ...
                 'NumberTitle', 'off', ...
                 'Color', '#FAF3E0', ...
                 'Units', 'normalized', ...
                 'Position', [0.1 0.1 0.7 0.7]);

    %add a title to the figure
    uicontrol('Style', 'text', ...
              'Units', 'normalized', ...
              'FontSize', 16, ...
              'FontWeight', 'bold', ...
              'BackgroundColor', '#FAF3E0', ...
              'Position', [0.3 0.9 0.4 0.1], ...
              'String', figurename);

    if avin == 0
    available_movies(fig);
    else
    buy_ticket(fig);
    end
end