%main file front_page.m
close all;

figure ('Name','MOVIE TRACKING',... 
        'Numbertitle', 'off',... 
        'Color','#FAF3E0',... 
        'Units','normalized',... 
        'Position',[0.2 0.2 0.7 0.7]); 
%title
uicontrol('Style','text', ...
          'Units','normalized', ...
          'Fontsize', 24, ...
          'Fontweight','bold', ...
          'BackgroundColor', 'white', ...
          'Position',[0.35 0.80 0.30 0.09], ...
          'String', 'MOVIE TRACKING');

%user menu
h = uimenu('Label', 'User_Menu');
uimenu(h, 'Label', 'Open Documentation', 'Callback', 'documentation');
uimenu(h, 'Label', 'Available Movies', 'Callback', 'avin=0;createfig(avin)');
uimenu(h, 'Label', 'Buy ticket', 'Callback', 'avin=1;createfig(avin)');
uimenu(h, 'Label', 'Display Picture1', 'Callback', ...
    'img = imread(''pusheen.jpg''); figure(''Name'', ''Pusheen'', ''NumberTitle'', ''off'', ''Color'', ''#FFFFFF'', ''Units'', ''normalized'', ''Position'', [0.2 0.2 0.6 0.6]); imshow(img, []); title(''Pusheen'', ''FontSize'', 16, ''FontWeight'', ''bold'');');
uimenu(h, 'Label', 'Display Picture2', 'Callback', ...
    'img = imread(''balaur.jpg''); figure(''Name'', ''Balaur'', ''NumberTitle'', ''off'', ''Color'', ''#FFFFFF'', ''Units'', ''normalized'', ''Position'', [0.2 0.2 0.6 0.6]); imshow(img, []); title(''Balaur'', ''FontSize'', 16, ''FontWeight'', ''bold'');');
uimenu(h, 'Label', 'Display Picture3', 'Callback', ...
    'img = imread(''pugsheen.jpg''); figure(''Name'', ''Pugsheen'', ''NumberTitle'', ''off'', ''Color'', ''#FFFFFF'', ''Units'', ''normalized'', ''Position'', [0.2 0.2 0.6 0.6]); imshow(img, []); title(''Pugsheen'', ''FontSize'', 16, ''FontWeight'', ''bold'');');
uimenu(h, 'Label', 'Display Picture4', 'Callback', ...
    'img = imread(''types.jpg''); figure(''Name'', ''Pugsheen'', ''NumberTitle'', ''off'', ''Color'', ''#FFFFFF'', ''Units'', ''normalized'', ''Position'', [0.2 0.2 0.6 0.6]); imshow(img, []); title('''', ''FontSize'', 16, ''FontWeight'', ''bold'');');


%create axes for the background image
ax = axes('Position', [0 0 1 1]);
imshow('background.jpeg', 'Parent', ax);

%button to display the documentation 
uicontrol('Style','pushbutton',... 
          'Units','normalized',... 
          'Fontsize', 14,... 
          'BackgroundColor','#FFD1DF',... 
          'Position',[0.4 0.6 0.20 0.1],... 
          'String','Documentation',... 
          'Callback','documentation'); 

%creates the figure for the Available movies option
uicontrol('Style','pushbutton',... 
          'Units','normalized',... 
          'Fontsize', 14,... 
          'BackgroundColor','#FFD1DF',... 
          'Position',[0.17 0.4 0.20 0.1],... 
          'String','Available movies',...          
          'Callback','avin=0;createfig(avin)'); 

%creates the figure for the Buy ticket option
uicontrol('Style','pushbutton',... 
          'Units','normalized',...
          'Fontsize', 14,...
          'BackgroundColor','#FFD1DF',...
          'Position',[0.63 0.4 0.20 0.1],...
          'String','Buy ticket',...          
          'Callback','avin=1;createfig(avin)');

%close button 
uicontrol('Style','pushbutton',...  
          'Units','normalized',... 
          'Fontsize', 12,... 
          'BackgroundColor','#D6CADD',... 
          'Position',[0.82 0.03 0.1 0.06],... 
          'string','Close',... 
          'Callback','close');