function most_watched_movies(fig)
    movies = {'Ten things I hate about you', 'Titanic', 'Where The Crawdads Sing', ...
              'Watcher', 'Lord of the rings', 'The wicked', 'The Conductor', ...
              'Wonder', 'Fast & Furious 9', 'Spider-Man', 'Home Alone', ...
              'Scary Movie', 'Orphan', 'Smile 2'};
    
    days = {'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'};

    %matrix initializtion
    fig.UserData.views = zeros(length(days), length(movies)); %rows for days, columns for movies
    fig.UserData.movies = movies;
    fig.UserData.days = days;

    uibuttongroup('Visible', 'on', ...
                  'BackgroundColor', '#D6CADD', ...
                  'ForegroundColor', 'black', ...
                  'Title', '', ...
                  'FontSize', 14, ...
                  'TitlePosition', 'centertop', ...
                  'Position', [0.45 0.05 0.47 0.82]);
   
    %'Select day and movie:'
    uicontrol('Style', 'text', ...
              'Units', 'normalized', ...
              'FontSize', 14, ...
              'FontWeight', 'bold', ...
              'BackgroundColor', '#D6CADD', ...
              'Position', [0.485 0.79 0.4 0.05], ...
              'String', 'Select day and movie:');

    %day dropdown
    days_dropdown = uicontrol('Style', 'popupmenu', ...
                              'Units', 'normalized', ...
                              'Position', [0.47, 0.75, 0.13, 0.04], ...
                              'FontSize', 12, ...
                              'BackgroundColor', '#FFFFFF', ...
                              'String', days, ...
                              'Enable', 'on', ...
                              'Callback', @(src, ~) day_selection_callback(src, fig));

    fig.UserData.days_dropdown = days_dropdown;

    %movie dropdown
    movies_dropdown = uicontrol('Style', 'popupmenu', ...
                                'Units', 'normalized', ...
                                'Position', [0.64, 0.75, 0.2, 0.04], ...
                                'FontSize', 12, ...
                                'BackgroundColor', '#FFFFFF', ...
                                'String', movies, ...
                                'Enable', 'on', ...
                                'Callback', @(src, ~) movie_selection_callback(src, fig));

    %'Number of views'
    uicontrol('Style', 'text', ...
              'Units', 'normalized', ...
              'Position', [0.47 0.67 0.12 0.05], ...
              'BackgroundColor', '#D6CADD', ...
              'ForegroundColor', 'black', ...
              'FontSize', 12, ...
              'String', 'Number of Views:');

    %edit object for entering number of views
    uicontrol('Style', 'edit', ...
              'Units', 'normalized', ...
              'Position', [0.6 0.685 0.05 0.045], ...
              'BackgroundColor', [0.9, 0.9, 0.9], ...
              'ForegroundColor', 'black', ...
              'FontSize', 12, ...
              'String', '', ...
              'Callback', @(src, ~) views_callback(src, fig));

    %button 'Show Most Watched Movies'
    uicontrol('Style', 'pushbutton', ...
              'Units', 'normalized', ...
              'Position', [0.47, 0.6, 0.4, 0.05], ...
              'BackgroundColor', '#ADD8E6', ...
              'ForegroundColor', 'black', ...
              'FontSize', 14, ...
              'String', 'Show Most Watched Movies', ...
              'Callback', @(~, ~) display_results(fig));

    %button 'Plot Most Watched Movies'
    uicontrol('Style', 'pushbutton', ...
              'Units', 'normalized', ...
              'Position', [0.47, 0.52, 0.4, 0.05], ...
              'BackgroundColor', '#ADD8E6', ...
              'ForegroundColor', 'black', ...
              'FontSize', 14, ...
              'String', 'Plot Most Watched Movies', ...
              'Callback', @(~, ~) plot_results(fig));
end

%callback for Day Selection
function day_selection_callback(src, fig)
    selected_day = src.String{src.Value}; %get selected_day
    fig.UserData.selected_day = selected_day; % store selected day
    disp(['Day selected: ', selected_day]); 
end

%callback for Movie Selection
function movie_selection_callback(src, fig)
    selected_movie = src.String{src.Value}; %get selected_movie
    fig.UserData.selected_movie = selected_movie; %store selected movie
    disp(['Movie selected: ', selected_movie]);
end

%callback for Number of Views
function views_callback(src, fig)
    input_value = str2double(src.String); %convert input to number

    %retrieve selected day and movie
    day_index = find(strcmp(fig.UserData.days, fig.UserData.selected_day));%find index of the day in the array
    movie_index = find(strcmp(fig.UserData.movies, fig.UserData.selected_movie));%same for movie

    %update views for the selected day and movie
    fig.UserData.views(day_index, movie_index) = input_value;

    disp(['Views updated: ', num2str(input_value), ' for ', fig.UserData.selected_movie, ' on ', fig.UserData.selected_day]);
end

%display results
function display_results(fig)
    views = fig.UserData.views;
    movies = fig.UserData.movies;
    days = fig.UserData.days;

    %display most-watched movie for each day
    results = '';%empty string
    for i = 1:size(views, 1) %i=day_index
        [max_views, max_index] = max(views(i, :));
        if max_views > 0
            results = [results, days{i}, ': ', movies{max_index}, ...
                       ' with ', num2str(max_views), ' views.'];
        else
            results = [results, days{i}, ': No views recorded.'];
        end
    end

    %show results in a dialog box
    msgbox(results, 'Most Watched Movies', 'help');
end

%plot results
function plot_results(fig)
    views = fig.UserData.views;
    movies = fig.UserData.movies;
    days = fig.UserData.days;

    %find the most-watched movie and its views for each day
    most_watched_views = zeros(size(views, 1), 1);
    most_watched_movies = cell(size(views, 1), 1);

    for i = 1:size(views, 1)
        [most_watched_views(i), max_index] = max(views(i, :));
        if most_watched_views(i) > 0
            most_watched_movies{i} = movies{max_index};
        else
            most_watched_movies{i} = 'No views';
        end
    end

    %create bar chart
    figure('Position', [100, 100, 1000, 600]);
    bar(most_watched_views,'FaceColor', '#FFD1DF');
    set(gca, 'XTickLabel', days, 'XTick', 1:length(days));
    xlabel('Days');
    ylabel('Number of Views');
    title('Most Watched Movies per Day');
    grid on;

    %add movie names as text labels above bars
    for i = 1:length(most_watched_views)
        text(i, most_watched_views(i) + 0.5, most_watched_movies{i}, ...
             'HorizontalAlignment', 'center', 'FontSize', 10, 'Color', 'black');
    end
end